# config/deploy/vagrant.rb
# Generated by cap_vagrant
server "127.0.0.1", :app
set :user, "vagrant"
set :password, "vagrant"
ssh_options[:keys] = ['"~/.vagrant.d/insecure_private_key"']
ssh_options[:port] = 2222
set :use_sudo, false
set :node_user, "vagrant"
